name: Execute RBA Job

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:


jobs:
  Execute_RBA_Job:
    runs-on: ubuntu-latest


    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run job in RBA
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Rundeck-Auth-Token: ${{ secrets.RBA_API_TOKEN }}" \
            https://rdse.runbook.pagerduty.cloud/api/14/job/d8987916-d0a6-4de2-b66a-bd75dc9054b2/run
