name: Execute PAOP Job

on:
  push:
    branches: [ "main" ]
    
  workflow_dispatch:


jobs:
  Execute_RBA_Job:
    runs-on: ubuntu-latest


    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run job in RBA
        run: |
          curl -X POST \
            -H "Content-Type: application/json" \
            -H "X-Rundeck-Auth-Token: ${{ secrets.RBA_PAOP_TOKEN }}" \
            https://demos.myrundeck.com/api/14/job/be7d4ff0-a4db-4aa5-97b3-933c162e9435/run
